### ISSUE TITLE
Hardware to add (optional but useful)

### ISSUE THREAD

**Issue by adulau** [cudeso/CSIRT-Jump-Bag#1]
- Write Blocker and/or ComboDock (such as [Forensic ComboDock, model FCDv5.5](https://wiebetech.com/products/forensic-combodock-v5-5/))
- If you have more budget, [TableauForensicImager](https://security.opentext.com/tableau/hardware/details/tx1)
- or a good hardware with guymager.

**Comment by cudeso** [comment]
Thank you! Added via https://github.com/cudeso/CSIRT-Jump-Bag/commit/296afd234addf96715b89583c32063883b38b796
